[package]

name = "acontrol"
version = "0.0.1"
authors = [ "otavio.ribeiro@gmail.com" ]

[dependencies]

clap = "2.26.0"
spidev = "0.3.0"
sysfs_gpio = "0.5.3"
iron = "*"
router = "*"
rustc-serialize = "*"
lazy_static = "*"
nix = "*"
