[target.arm-unknown-linux-gnueabi]
pre-build = ["dpkg --add-architecture armel && apt-get update && apt-get install --assume-yes systemd libsystemd-dev libsystemd-dev:armel libudev-dev libudev-dev:armel libdbus-1-dev libdbus-1-dev:armel libsqlite3-dev libsqlite3-0:armel libsqlite3-dev:armel"]

[target.arm-unknown-linux-gnueabihf]
pre-build = ["dpkg --add-architecture armhf && apt-get update && apt-get install --assume-yes systemd libsystemd-dev libsystemd-dev:armhf libudev-dev libudev-dev:armhf libdbus-1-dev libdbus-1-dev:armhf libsqlite3-dev libsqlite3-dev:armhf"]

[target.arm-unknown-linux-gnueabihf.env]
passthrough = [
    "PKG_CONFIG_ALLOW_CROSS",
    "PKG_CONFIG_PATH",
    "PKG_CONFIG_LIBDIR"
]

[target.arm-unknown-linux-gnueabi.env]
passthrough = [
    "PKG_CONFIG_ALLOW_CROSS",
    "PKG_CONFIG_PATH",
    "PKG_CONFIG_LIBDIR"
]
