[target.arm-unknown-linux-gnueabi]
linker = "arm-linux-gnueabi-gcc"
rustflags = ["-L","/lib/arm-linux-gnueabi","-L","/usr/lib/arm-linux-gnueabi"]

[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = ["-L","/lib/arm-linux-gnueabihf","-L","/usr/lib/arm-linux-gnueabihf"]
